---

- hosts: prod
  become: yes
  vars:
    doc_root: "/var/www/html" 

  tasks:
  - name: Install Apache Packages on Ubuntu
    apt: name=apache2 state=present
    when: ansible_os_family=="Debian"

  - name: Install Apache Packages on Centos
    yum: name=httpd state=present
    when: ansible_os_family=="RedHat"

  - name: Deploy Default Index file. 
    copy: src=templates/amit.txt dest=/var/www/html/index.html

  - name: Deploy Default Index file. 
    template: src=templates/info.j2 dest=/var/www/html/info.html

  - name: Start Apache Service on Ubuntu 
    service: name=apache2 state=started
    when: ansible_os_family=="Debian"

  - name: Start Apache Service on CentOS
    service: name=httpd state=started
    when: ansible_os_family=="RedHat"
